export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CHANGE_QTY =  "CHANGE_QTY";
export const CHANGE_CHECKOUT_STAGE = "CHANGE_CHECKOUT_STAGE";
export const ADD_ADDRESS =  "ADD_ADDRESS";
export const ORDER_SUCCESSFUL =  "ORDER_SUCCESSFUL";
export const ADD_MARGIN = "ADD_MARGIN";


